import { Problem } from './types';

export const PRELOADED_PROBLEMS: Problem[] = [
  {
    id: 'MAS101_EXP_P1',
    title: 'Basic Limit by Factoring',
    rating: 800,
    category: 'Calculus',
    statement: 'Evaluate the following limit by factoring the numerator:\n\n$$\\lim_{x \\to 3} \\frac{x^2 - 9}{x - 3}$$',
    sampleInput: 'Show the step-by-step factorization of the numerator and evaluate the limit.',
    sampleOutput: '6',
    solution: 'We have $x^2 - 9 = (x - 3)(x + 3)$. For $x \\neq 3$:\n$$\\frac{x^2 - 9}{x - 3} = \\frac{(x - 3)(x + 3)}{x - 3} = x + 3$$\nNow, take the limit as $x \\to 3$:\n$$\\lim_{x \\to 3} (x + 3) = 3 + 3 = 6$$',
    intuition: 'When evaluating limits, a 0/0 indeterminate form often indicates a common factor in the numerator and denominator. Factoring and dividing out this factor allows us to find the limit of the corresponding continuous function.',
    tags: ['limits', 'factoring', 'indeterminate-form', 'calculus-1']
  },
  {
    id: 'MAS101_EXP_P2',
    title: 'Limit at Infinity for Rational Function',
    rating: 900,
    category: 'Calculus',
    statement: 'Determine the limit of the rational function as $x$ approaches infinity:\n\n$$\\lim_{x \\to \\infty} \\frac{3x^2 - 4x + 5}{2x^2 + 7x - 1}$$',
    sampleInput: 'Divide both the numerator and denominator by the highest power of x, then evaluate.',
    sampleOutput: '3/2',
    solution: 'Divide the numerator and denominator by $x^2$:\n$$\\lim_{x \\to \\infty} \\frac{3x^2 - 4x + 5}{2x^2 + 7x - 1} = \\lim_{x \\to \\infty} \\frac{3 - \\frac{4}{x} + \\frac{5}{x^2}}{2 + \\frac{7}{x} - \\frac{1}{x^2}}$$\nSince $\\lim_{x \\to \\infty} \\frac{1}{x} = 0$ and $\\lim_{x \\to \\infty} \\frac{1}{x^2} = 0$, we get:\n$$\\frac{3 - 0 + 0}{2 + 0 - 0} = \\frac{3}{2}$$',
    intuition: 'At infinity, the highest-power term of a polynomial dominates its growth. Computing the ratio of leading coefficients determines the horizontal asymptote.',
    tags: ['limits', 'infinity', 'rational-functions', 'horizontal-asymptotes']
  },
  {
    id: 'MAS101_EXP_P3',
    title: 'Linear Approximation of Exponential',
    rating: 950,
    category: 'Calculus',
    statement: 'Find the linear approximation (Tuyến tính hóa) $L(x)$ of the function $f(x) = e^{2x}$ at $x = 0$.',
    sampleInput: 'Compute the derivative at x = 0, and construct the linearization formula L(x) = f(0) + f\'(0)*x.',
    sampleOutput: '1 + 2x',
    solution: 'First, we evaluate $f(0) = e^0 = 1$.\nNext, find the derivative of $f(x)$:\n$$f\'(x) = 2e^{2x} \\implies f\'(0) = 2(1) = 2$$\nUsing the linearization formula $L(x) = f(0) + f\'(0)(x - 0)$:\n$$L(x) = 1 + 2x$$',
    intuition: 'Linearization replaces a complex curve (like the exponential function) with its tangent line at a given point. This approximates the function very accurately in a small neighborhood.',
    tags: ['derivatives', 'linearization', 'exponential', 'tangent-line']
  },
  {
    id: 'MAS101_EXP_P4',
    title: 'Indefinite Integral by u-Substitution',
    rating: 1000,
    category: 'Calculus',
    statement: 'Evaluate the following indefinite integral using u-substitution:\n\n$$\\int x^2 e^{x^3} \\, dx$$',
    sampleInput: 'Identify the substitution variable u, find du, substitute, and integrate.',
    sampleOutput: '\\frac{1}{3} e^{x^3} + C',
    solution: 'Let $u = x^3 \\implies du = 3x^2 dx \\implies x^2 dx = \\frac{1}{3} du$.\nSubstitute these into the integral:\n$$\\int x^2 e^{x^3} \\, dx = \\int e^u \\left(\\frac{1}{3} du\\right) = \\frac{1}{3} \\int e^u \\, du = \\frac{1}{3} e^u + C$$\nSubstitute back $u = x^3$:\n$$\\frac{1}{3} e^{x^3} + C$$',
    intuition: 'Substitution is the reverse of the Chain Rule for derivatives. If we see a composite function multiplied by a scalar multiple of its inner derivative, substitution is the ideal integration tool.',
    tags: ['u-substitution', 'indefinite-integration', 'exponential', 'calculus-1']
  },
  {
    id: 'MAS101_EXP_P5',
    title: 'Product Squeeze Theorem Limit',
    rating: 1050,
    category: 'Calculus',
    statement: 'Evaluate the following limit using the Squeeze Theorem (Định lý kẹp):\n\n$$\\lim_{x \\to 0} x^2 \\cos\\left(\\frac{1}{x}\\right)$$',
    sampleInput: 'Set up the bounds for the cosine function, multiply by x^2, and take the limit of the bounding functions.',
    sampleOutput: '0',
    solution: 'We know that for any $x \\neq 0$, the cosine function is bounded:\n$$-1 \\le \\cos\\left(\\frac{1}{x}\\right) \\le 1$$\nSince $x^2 > 0$ for all $x \\neq 0$, we can multiply the inequalities by $x^2$:\n$$-x^2 \\le x^2 \\cos\\left(\\frac{1}{x}\\right) \\le x^2$$\nSince $\\lim_{x \\to 0} (-x^2) = 0$ and $\\lim_{x \\to 0} (x^2) = 0$, by the Squeeze Theorem, we conclude:\n$$\\lim_{x \\to 0} x^2 \\cos\\left(\\frac{1}{x}\\right) = 0$$',
    intuition: 'When a function oscillates rapidly but is bounded, multiplying it by a factor that approaches zero squeezes the entire product to zero at that limit.',
    tags: ['squeeze-theorem', 'limits', 'trigonometric-limits', 'calculus-1']
  },
  {
    id: 'MAS101_EXP_P6',
    title: 'Linear Approximation of Sine Function',
    rating: 1100,
    category: 'Calculus',
    statement: 'Find the linearization $L(x)$ of the function $f(x) = \\sin(x)$ at the point $c = \\frac{\\pi}{3}$.',
    sampleInput: 'Evaluate sine and derivative cosine functions at pi/3 to construct standard approximation.',
    sampleOutput: '\\frac{\\sqrt{3}}{2} + \\frac{1}{2}\\left(x - \\frac{\\pi}{3}\\right)',
    solution: 'We have $f(\\pi/3) = \\sin(\\pi/3) = \\frac{\\sqrt{3}}{2}$.\nThe derivative of $f(x)$ is:\n$$f\'(x) = \\cos(x) \\implies f\'(\\pi/3) = \\cos(\\pi/3) = \\frac{1}{2}$$\nUsing the linearization formula $L(x) = f(c) + f\'(c)(x - c)$:\n$$L(x) = \\frac{\\sqrt{3}}{2} + \\frac{1}{2}\\left(x - \\frac{\\pi}{3}\\right)$$',
    intuition: 'This tangent line approximates the sine wave very accurately close to $\\pi/3$, facilitating fast, mechanical coordinate calculations without evaluating circular functions.',
    tags: ['linearization', 'derivatives', 'sine-series', 'calculus-1']
  },
  {
    id: 'MAS101_EXP_P7',
    title: 'Sine-Cosine Product Substitution',
    rating: 1200,
    category: 'Calculus',
    statement: 'Evaluate the following indefinite integral using u-substitution:\n\n$$\\int \\sin^3(x) \\cos^2(x) \\, dx$$',
    sampleInput: 'Separate an odd power of sine, rewrite the remaining powers using pythagorean trig identities, and substitute u=cosx.',
    sampleOutput: '-\\frac{1}{3}\\cos^3(x) + \\frac{1}{5}\\cos^5(x) + C',
    solution: 'We rewrite $\\sin^3(x)$ as $\\sin^2(x) \\sin(x) = (1 - \\cos^2(x)) \\sin(x)$.\nSo the integral becomes:\n$$\\int (1 - \\cos^2(x)) \\cos^2(x) \\sin(x) \\, dx = \\int (\\cos^2(x) - \\cos^4(x)) \\sin(x) \\, dx$$\nLet $u = \\cos(x) \\implies du = -\\sin(x) dx \\implies \\sin(x) dx = -du$.\nSubstitute these in:\n$$\\int (u^2 - u^4) (-du) = \\int (u^4 - u^2) \\, du = \\frac{u^5}{5} - \\frac{u^3}{3} + C$$\nSubstitute back $u = \\cos(x)$:\n$$-\\frac{1}{3}\\cos^3(x) + \\frac{1}{5}\\cos^5(x) + C$$',
    intuition: 'When integrating products of sines and cosines with at least one odd power, we reserve one factor of the odd power as the differential (du) and convert the remaining factors using basic Pythagorean identities.',
    tags: ['trigonometric-integration', 'u-substitution', 'pythagorean-identity', 'calculus-1']
  },
  {
    id: 'KAIST101_Q1_P1',
    title: 'Double Trig Integral',
    rating: 1500,
    category: 'Calculus',
    statement: 'Integrate the following product of squared trigonometric functions:\n\n$$\\int \\sin^2(7x) \\sin^2(3x) \\, dx$$',
    sampleInput: 'A step-by-step integration or final simplified LaTeX expression.',
    sampleOutput: '\\frac{1}{4}x - \\frac{1}{24}\\sin(6x) + \\frac{1}{64}\\sin(8x) - \\frac{1}{56}\\sin(14x) + \\frac{1}{160}\\sin(20x) + C',
    solution: 'Use the half-angle formulas:\n$$\\sin^2(7x) = \\frac{1 - \\cos(14x)}{2}, \\quad \\sin^2(3x) = \\frac{1 - \\cos(6x)}{2}$$\nMultiply these to get:\n$$\\frac{1}{4}(1 - \\cos(14x) - \\cos(6x) + \\cos(14x)\\cos(6x))$$\nThen apply the product-to-sum identity for $\\cos(14x)\\cos(6x) = \\frac{1}{2}(\\cos(8x) + \\cos(20x))$.\nIntegrate each term individually.',
    intuition: 'In signal processing and quantum mechanics, products of periodic functions represent frequency modulation. By converting products of high-frequency sinusoids into sums of individual frequencies (spectral decomposition), we can linearize and solve complex differential systems easily.',
    tags: ['trigonometric-integration', 'half-angle-identities', 'product-to-sum', 'calculus-1']
  },
  {
    id: 'KAIST101_Q1_P2',
    title: 'Exponential-Sine Loop Integration',
    rating: 1400,
    category: 'Calculus',
    statement: 'Compute the indefinite integral using integration by parts (and resolve the resulting loop recursion):\n\n$$\\int e^{3x} \\sin(2x) \\, dx$$',
    sampleInput: 'LaTeX solution steps explaining the integration by parts or final closed formula.',
    sampleOutput: '\\frac{e^{3x}(3 \\sin(2x) - 2 \\cos(2x))}{13} + C',
    solution: 'Let $I = \\int e^{3x} \\sin(2x)\\,dx$. Using integration by parts twice:\n1. Choose $u = \\sin(2x), dv = e^{3x}dx \\implies du = 2\\cos(2x)dx, v = \\frac{1}{3}e^{3x}$.\n$$I = \\frac{1}{3}e^{3x}\\sin(2x) - \\frac{2}{3}\\int e^{3x}\\cos(2x)\\,dx$$\n2. For the second integral, let $u = \\cos(2x), dv = e^{3x}dx \\implies du = -2\\sin(2x)dx, v = \\frac{1}{3}e^{3x}$.\n$$I = \\frac{1}{3}e^{3x}\\sin(2x) - \\frac{2}{3} \\left( \\frac{1}{3}e^{3x}\\cos(2x) + \\frac{2}{3}I \\right)$$\nExpand and solve for $I$:\n$$I + \\frac{4}{9}I = e^{3x}\\left(\\frac{1}{3}\\sin(2x) - \\frac{2}{9}\\cos(2x)\\right) \\implies \\frac{13}{9}I = e^{3x}\\frac{3\\sin(2x) - 2\\cos(2x)}{9}$$\n$$I = \\frac{e^{3x}(3\\sin(2x) - 2\\cos(2x))}{13} + C$$',
    intuition: 'This is the analytical continuous representation of a damped harmonic oscillator (e.g. suspension springs, RLC circuits). In Laplace and Fourier transforms, integrating exponentials with sinusoids maps a time-domain ODE directly into the complex frequency plane s=3+2i.',
    tags: ['integration-by-parts', 'recursion-loop', 'damped-oscillation', 'calculus-1']
  },
  {
    id: 'KAIST101_Q1_P3',
    title: 'Algebraic Trigonometric Substitution',
    rating: 1200,
    category: 'Calculus',
    statement: 'Evaluate the following indefinite integral using u-substitution followed by partial fraction decomposition:\n\n$$\\int \\frac{\\cos y}{\\sin^2 y + \\sin y - 6} \\, dy$$',
    sampleInput: 'u-substitution choice, partial fraction coefficients, and final logarithm.',
    sampleOutput: '\\frac{1}{5} \\ln \\left| \\frac{\\sin y - 2}{\\sin y + 3} \\right| + C',
    solution: 'Let $u = \\sin y \\implies du = \\cos y\\,dy$. The integral becomes:\n$$\\int \\frac{1}{u^2 + u - 6} \\, du = \\int \\frac{1}{(u - 2)(u + 3)} \\, du$$\nApply partial fraction decomposition:\n$$\\frac{1}{(u-2)(u+3)} = \\frac{A}{u-2} + \\frac{B}{u+3}$$\nSince $A(u+3) + B(u-2) = 1$, setting $u=2 \\implies A=\\frac{1}{5}$, and $u=-3 \\implies B=-\\frac{1}{5}$.\nSo we integrate:\n$$\\frac{1}{5} \\int \\left( \\frac{1}{u-2} - \\frac{1}{u+3} \\right) du = \\frac{1}{5} \\ln|u-2| - \\frac{1}{5} \\ln|u+3| + C$$\nSubstitute back $u = \\sin y$.',
    intuition: 'Substitution acts as a coordinate transformation (diffeomorphism) mapping a complex curvy interval onto a straight line where fractions decompose. This is the cornerstone of structural simplification in mathematical solvers.',
    tags: ['u-substitution', 'partial-fractions', 'rational-trig', 'calculus-1']
  },
  {
    id: 'KAIST101_Q3_P1',
    title: 'Inverse Hyperbolic Maclaurin Series',
    rating: 1700,
    category: 'Series',
    statement: '1. Using the binomial series formula, find the Maclaurin series expansion for:\n$$f(x) = (1 + x^2)^{-1/2}$$\n2. Use term-by-term integration of $f(x)$ to prove the Maclaurin series for $\\sinh^{-1}(x)$, and find its interval of convergence with endpoint behavior analyses.',
    sampleInput: 'Maclaurin coefficients, integrated series sum representation, and convergence interval.',
    sampleOutput: '\\sinh^{-1}(x) = x + \\sum_{k=1}^{\\infty} \\frac{(-1)^k (2k-1)!!}{(2k)!! (2k+1)} x^{2k+1} \\quad \\text{on } [-1, 1]',
    solution: 'By the binomial series for $(1+u)^{-1/2}$ with $u=x^2$:\n$$(1+x^2)^{-1/2} = 1 + \\sum_{k=1}^{\\infty} \\binom{-1/2}{k} x^{2k} = 1 + \\sum_{k=1}^{\\infty} \\frac{(-1)^k (2k-1)!!}{2^k k!} x^{2k}$$\nSince $\\frac{d}{dx}[\\sinh^{-1}(x)] = (1+x^2)^{-1/2}$, integrate term-by-term:\n$$\\sinh^{-1}(x) + C = x + \\sum_{k=1}^{\\infty} \\frac{1}{2k+1} \\binom{-1/2}{k} x^{2k+1}$$\nSubstituting $x=0$ yields $C=0$. The limit ratio test results in a radius of convergence of $R=1$.\nAt $x = \\pm 1$, the terms alternate and decreasingly converge to 0, satisfying Leibniz\'s theorem. Thus the interval of convergence is $[-1, 1]$.',
    intuition: 'Binomial series let us represent non-polynomial algebraic expressions as infinite polynomials. In deep learning theory, activations or activation functions like Gelu or inverse-hyperbolic curves can be analyzed in their Taylor forms to prove gradient stability near the origin.',
    tags: ['binomial-series', 'maclaurin-expansion', 'interval-of-convergence', 'hyperbolic-trig']
  },
  {
    id: 'KAIST101_Q3_P2',
    title: 'Indeterminate Limit with Taylor Expansion',
    rating: 1300,
    category: 'Series',
    statement: '1. Determine the third Taylor polynomial $P_3(x)$ about $x=0$ for the function $\\tan(x)$.\n2. Find the values of $a, b \\in \\mathbb{R}$ such that the following limit holds:\n$$\\lim_{x \\to 0} \\frac{\\tan(x) - \\sin(ax)}{bx^3} = 1$$',
    sampleInput: 'Explain derivative calculations or standard Taylor expansion matching, then solve for a, b.',
    sampleOutput: 'a = 1, b = 1/2',
    solution: 'For $\\tan(x)$, computing derivatives up to order 3 at $0$ yields:\n$$f(0)=0, \\, f\'(0)=1, \\, f\'\'(0)=0, \\, f\'\'\'(0)=2 \\implies P_3(x) = x + \\frac{x^3}{3}$$\nFor the second part, expand $\\tan(x)$ and $\\sin(ax)$ using Taylor series:\n$$\\tan(x) = x + \\frac{x^3}{3} + O(x^5)$$\n$$\\sin(ax) = ax - \\frac{a^3 x^3}{6} + O(x^5)$$\nSubstitute into the limit construct:\n$$\\lim_{x \\to 0} \\frac{(1-a)x + (\\frac{1}{3} + \\frac{a^3}{6})x^3 + O(x^5)}{b x^3} = 1$$\nFor this limit to be finite and equal to 1, the numerator\'s linear term must cancel, implying $1-a = 0 \\implies a=1$.\nNow, the limit reduces to the coefficient ratio:\n$$\\frac{\\frac{1}{3} + \\frac{1^3}{6}}{b} = 1 \\implies \\frac{1/2}{b} = 1 \\implies b = \\frac{1}{2}$$',
    intuition: 'Taylor series approximate complex transcendental curves with simpler local polynomials. In computer graphics, evaluating trigonometric functions near zero is bypassed by hardware using these polynomial approximations, preventing divide-by-zero or numerical instability.',
    tags: ['taylor-series', 'indeterminate-limits', 'sine-expansion', 'tangent-expansion']
  },
  {
    id: 'KAIST101_Q4_P1',
    title: 'Polar Area: Circle and Cardioid',
    rating: 1600,
    category: 'Calculus',
    statement: 'Consider the circle $r = 3a \\cos(\\theta)$ and the cardioid of equation $r = a(1 + \\cos(\\theta))$ where $a$ is a positive constant.\n\nCalculate the area $A$ of the region that lies inside the circle and outside the cardioid.',
    sampleInput: 'Explain intersection angles, double integral or single polar area formula, and evaluate.',
    sampleOutput: '\\pi a^2',
    solution: 'First, find the points of intersection:\n$$3a\\cos(\\theta) = a(1 + \\cos(\\theta)) \\implies 2\\cos(\\theta) = 1 \\implies \\cos(\\theta) = \\frac{1}{2}$$\nThus, the intersection angles inside the quadrant are $\\theta = -\\pi/3$ and $\\theta = \\pi/3$.\nBy symmetry, the area is:\n$$A = 2 \\int_{0}^{\\pi/3} \\frac{1}{2} \\left[ (3a\\cos(\\theta))^2 - (a(1+\\cos(\\theta)))^2 \\right] d\\theta$$\n$$A = \\int_{0}^{\\pi/3} a^2 \\left( 9\\cos^2(\\theta) - (1 + 2\\cos(\\theta) + \\cos^2(\\theta)) \\right) d\\theta$$\n$$A = a^2 \\int_{0}^{\\pi/3} (8\\cos^2(\\theta) - 2\\cos(\\theta) - 1) d\\theta$$\nSince $\\cos^2(\\theta) = \\frac{1+\\cos(2\\theta)}{2}$, the integral simplifies to:\n$$A = a^2 \\int_{0}^{\\pi/3} (3 + 4\\cos(2\\theta) - 2\\cos(\\theta)) d\\theta$$\n$$A = a^2 \\left[ 3\\theta + 2\\sin(2\\theta) - 2\\sin(\\theta) \\right]_{0}^{\\pi/3}$$\n$$A = a^2 \\left( \\pi + 2\\sin(2\\pi/3) - 2\\sin(\\pi/3) \\right) = a^2 (\\pi + \\sqrt{3} - \\sqrt{3}) = \\pi a^2$$',
    intuition: 'Polar integration measures areas swept by a rotating ray from the origin instead of tiny rectangular blocks. In LiDAR analysis and self-driving obstacle detection, sensor coordinate systems are naturally polar; calculating sweep areas determines safe driving envelopes.',
    tags: ['polar-coordinates', 'area-calculation', 'cardioid', 'double-integrals']
  },
  {
    id: 'KAIST101_Q5_P1',
    title: '3D Geometry: Plane-Point & Line-Point Distances',
    rating: 1800,
    category: '3D Geometry',
    statement: 'Let $E$ be the plane in $\\mathbb{R}^3$ given by the equation $x + 2y - z = 1$, and $A = (1, 1, 1)$ a point in 3-space.\n\n1. Calculate the perpendicular distance from the plane $E$ to the point $A$.\n2. Calculate the distance from point $A$ to the line of intersection in which $E$ and the $(x, z)$-plane intersect.',
    sampleInput: 'Describe plane perpendicular projection formula, represent the line of intersection, and execute vector projection.',
    sampleOutput: 'Part 1: 1/\\sqrt{6}, Part 2: \\sqrt{1.5}',
    solution: '1. The distance from point $A(x_0, y_0, z_0)$ to plane $Ax + By + Cz = D$ is:\n$$d = \\frac{|Ax_0 + By_0 + Cz_0 - D|}{\\sqrt{A^2 + B^2 + C^2}}$$\nFor plane $x+2y-z=1$ and point $(1,1,1)$:\n$$d = \\frac{|1(1) + 2(1) - 1(1) - 1|}{\\sqrt{1^2 + 2^2 + (-1)^2}} = \\frac{|1 + 2 - 1 - 1|}{\\sqrt{6}} = \\frac{1}{\\sqrt{6}}$$\n2. The line of intersection $\\ell$ of plane $E$ and the $(x, z)$-plane (where $y=0$) is characterized by:\n$$x + 2(0) - z = 1 \\implies x - z = 1, \\quad y = 0$$\nThis can be parameterized. Let $z = t \\implies x = 1+t$. The vector form is:\n$$\\vec{r}(t) = (1, 0, 0) + t(1, 0, 1)$$\nLet $P = (1, 0, 0)$ be a point on the line, and $\\vec{v} = (1, 0, 1)$ be the direction vector. The vector from $P$ to $A(1,1,1)$ is $\\vec{PA} = (0, 1, 1)$.\nThe distance is given by the projection formula:\n$$D = \\|\\vec{PA} - \\text{proj}_{\\vec{v}}(\\vec{PA})\\|$$\n$$\\text{proj}_{\\vec{v}}(\\vec{PA}) = \\frac{\\vec{PA} \\cdot \\vec{v}}{\\|\\vec{v}\\|^2} \\vec{v} = \\frac{0(1) + 1(0) + 1(1)}{1^2+0^2+1^2}(1,0,1) = \\frac{1}{2}(1,0,1)$$\n$$\\vec{PA} - \\text{proj}_{\\vec{v}}(\\vec{PA}) = (0,1,1) - (1/2, 0, 1/2) = (-1/2, 1, 1/2)$$\n$$D = \\sqrt{(-1/2)^2 + 1^2 + (1/2)^2} = \\sqrt{1/4 + 1 + 1/4} = \\sqrt{1.5} = \\frac{\\sqrt{6}}{2}$$',
    intuition: 'Planes and projections form the cornerstone of Convex Optimization and Support Vector Machines. Calculating the distance to a hyperplane is the exact loss optimization function used to maximize classifiers margin separating different data clusters.',
    tags: ['vector-projection', '3D-lines-planes', 'intersection-line', 'orthogonal-distance']
  },
  {
    id: 'KAIST101_Q5_P2',
    title: 'Submerged Ellipsoid Spherical Boundary',
    rating: 2400,
    category: 'Proofs',
    statement: 'Let $R$ be the solid ellipsoid in $\\mathbb{R}^3$ given by the equation:\n$$x^2 + y^2 + 2z^2 = 5$$\nAssume that $R$ is filled with water up to height $z = -1$. Let $B$ be the part of the solid that is submerged in water.\n\nDescribe the submersed solid $B$ in spherical coordinates $(\\rho, \\phi, \\theta)$ by finding the constants $a, b, c, d$ and boundary functions $f(\\phi), g(\\phi)$ such that:\n$$B = \\{(\\rho, \\phi, \\theta) \\mid a \\le \\theta \\le b, \\, c \\le \\phi \\le d, \\, f(\\phi) \\le \\rho \\le g(\\phi)\\}$$',
    sampleInput: 'Describe the range values for theta and phi, convert cartesian equations of ellipsoid and submerged surface to spherical, and extract limits.',
    sampleOutput: 'a=0, b=2\\pi, c=2\\pi/3, d=\\pi, f(\\phi)=-\\sec(\\phi), g(\\phi)=\\sqrt{\\frac{5}{1+\\cos^2\\phi}}',
    solution: '1. By rotational symmetry around the $z$-axis, the azimuthal angle $\\theta$ sweeps the full circle:\n$$a = 0, \\quad b = 2\\pi$$\n2. The water boundary is $z = -1$. In spherical coordinates, $z = \\rho \\cos\\phi = -1 \\implies \\rho = -\\sec\\phi$. Because we are in the submerged section below $z=-1$, $\\cos\\phi$ must be negative, so $\\phi > \\pi/2$. The intersection curve of the water surface $z=-1$ and ellipsoid $x^2+y^2+2z^2=5$ has $x^2+y^2+2(-1)^2=5 \\implies x^2+y^2=3$, which represents a cylinder of radius $r=\\sqrt{3}$. At this intersection, the cone angle $\\phi$ satisfies:\n$$\\tan\\phi = \\frac{r}{z} = \\frac{\\sqrt{3}}{-1} = -\\sqrt{3} \\implies \\phi = \\frac{2\\pi}{3}$$\nSince we are submerged, $\\phi$ ranges from this transition cone to the bottom pole:\n$$c = \\frac{2\\pi}{3}, \\quad d = \\pi$$\n3. The lower radial boundary is governed by the flat water surface $z = -1$, and the upper by the ellipsoid surface. ellipsoid equation: $x^2+y^2+2z^2 = \\rho^2 \\sin^2\\phi \\cos^2\\theta + \\rho^2 \\sin^2\\phi \\sin^2\\theta + 2\\rho^2 \\cos^2\\phi = \\rho^2(\\sin^2\\phi + 2\\cos^2\\phi) = \\rho^2(1 + \\cos^2\\phi) = 5$.\nRadial boundaries:\n$$f(\\phi) = -\\sec(\\phi)$$\n$$g(\\phi) = \\sqrt{\\frac{5}{1 + \\cos^2\\phi}}$$',
    intuition: 'Sub-volume rendering and boundary description are fundamental in 3D Computer Graphics and physics-based fluid simulation engines. Translating Cartesian grids into spherical coordinates simplifies boundary-value updates, resolving numerical collision states in constant O(1) time.',
    tags: ['spherical-coordinates', 'volume-modeling', 'coordinate-change', 'advanced-calculus']
  },
  {
    id: 'KAIST101_F_P1',
    title: 'Skew Lines Distance & Target Plane Projection',
    rating: 2100,
    category: '3D Geometry',
    statement: '1. Determine the shortest distance between the following two skew lines in $\\mathbb{R}^3$:\n$$\\ell_1(t) = (0, 0, 1) + t(2, 1, 0)$$\n$$\\ell_2(t) = (0, 2, 0) + t(1, -3, 1)$$\n2. Among all planes containing the line $\\ell_2$, find the equation of the plane that has the largest distance to the point $P(0, 0, 1)$.',
    sampleInput: 'Part 1: show cross-product of direction vectors, joint normal vector projection. Part 2: normal vector optimization logic.',
    sampleOutput: 'Part 1: 1/\\sqrt{6}, Part 2: 7x + y - 4z - 2 = 0',
    solution: '1. The direction vectors are $\\vec{v}_1 = (2,1,0)$ and $\\vec{v}_2 = (1,-3,1)$. A joint normal vector is:\n$$\\vec{n} = \\vec{v}_1 \\times \\vec{v}_2 = \\begin{vmatrix} \\vec{i} & \\vec{j} & \\vec{k} \\\\ 2 & 1 & 0 \\\\ 1 & -3 & 1 \\end{vmatrix} = (1, -2, -7)$$\nA vector connecting any point on $\\ell_1$ (e.g., $P_1(0,0,1)$) to $\\ell_2$ (e.g., $P_2(0,2,0)$) is $\\vec{P_1P_2} = (0, 2, -1)$. The shortest distance is the projection of this vector onto the joint unit normal:\n$$D = \\frac{|\\vec{P_1P_2} \\cdot \\vec{n}|}{\\|\\vec{n}\\|} = \\frac{|0(1) + 2(-2) + (-1)(-7)|}{\\sqrt{1^2 + (-2)^2 + (-7)^2}} = \\frac{|-4 + 7|}{\\sqrt{1+4+49}} = \\frac{3}{\\sqrt{54}} = \\frac{3}{3\\sqrt{6}} = \\frac{1}{\\sqrt{6}}$$\n2. For any plane $E$ containing line $\\ell_2$ and any point $P(0,0,1)$ not on the line, the distance from $P$ to the plane is maximized when the vector projection $PQ$ (where $Q$ is the projection of $P$ on line $\\ell_2$) is orthogonal to $E$. Thus the line $PQ$ serves as the plane normal. Let\'s find the closest point $Q$ on $\\ell_2$ to $P$:\n$$\\vec{Q} = (0,2,0) + t(1,-3,1)$$\n$$\\vec{PQ} = \\vec{Q} - \\vec{P} = (t, 2-3t, t-1)$$\nSince $\\vec{PQ}$ must be orthogonal to direction of $\\ell_2$ (which is $\\vec{v}_2=(1,-3,1)$):\n$$\\vec{PQ} \\cdot \\vec{v}_2 = t(1) + (2-3t)(-3) + (t-1)(1) = t - 6 + 9t + t - 1 = 11t - 7 = 0 \\implies t = \\frac{7}{11}$$\n$$Q = (7/11, 2/11, 7/11)$$\n$$\\vec{PQ} = (7/11, 1/11, -4/11)$$\nScaling this vector yields normal vector $\\vec{N} = (7, 1, -4)$.\nThe equation of the plane through $(0,2,0)$ is:\n$$7(x-0) + 1(y-2) - 4(z-0) = 0 \\implies 7x + y - 4z - 2 = 0$$',
    intuition: 'Skew lines are vectors in multidimensional space that do not intersect. The shortest distance represents their orthogonal subspace bridge. Plane distance optimization matches the exact problem structure of calculating optimal cutting hyperplanes in high-dimensional kernel manifolds.',
    tags: ['skew-lines-distance', 'cross-product', 'normal-optimization', 'plane-equation']
  },
  {
    id: 'KAIST101_F_P2',
    title: '3D Vector Triple Cross Collinearity Proof',
    rating: 2600,
    category: 'Proofs',
    statement: 'Determine whether the following statements are true or false for arbitrary vectors $a, b \\in \\mathbb{R}^3$. Provide a mathematical proof or counterexample:\n\n1. The vectors $b$ and $a \\times (a \\times b)$ are always collinear.\n2. The vectors $a \\times b$ and $(a \\times (a \\times b)) \\times b$ are always collinear.',
    sampleInput: 'Verify each statement, write appropriate cross-product identities (like BAC-CAB) or geometric projection logic, and prove.',
    sampleOutput: 'Statement 1 is FALSE (Counterexample provided), Statement 2 is TRUE (Proof provided)',
    solution: '1. FALSE. Consider counterexample $a = (1, 0, 0)$ and $b = (1, 1, 0)$. Then\n$$a \\times b = (0, 0, 1)$$\n$$a \\times (a \\times b) = (1, 0, 0) \\times (0, 0, 1) = (0, -1, 0)$$\nObviously, $(0,-1,0)$ is not collinear to $(1,1,0)$ because they are not scalar multiples of each other. Geometrically, $a \\times (a \\times b)$ lies in the plane spanned by $a$ and $b$ and is perpendicular to $a$, which does not align with $b$ unless $a \\cdot b = 0$.\n2. TRUE. Let $v = a \\times (a \\times b)$. We want to check collinearity of $a \\times b$ and $v \\times b$. We know $v$ is perpendicular to $a \\times b$ (as $v$ is a cross product involving $a \\times b$). Let\'s evaluate $v \\times b$:\nUsing vector triple product expansion $(\\vec{X} \\times \\vec{Y}) \\times \\vec{Z}$:\n$$v = (a \\cdot b)a - (a \\cdot a)b$$\nThus:\n$$v \\times b = ((a \\cdot b)a - (a \\cdot a)b) \\times b = (a \\cdot b)(a \\times b) - (a \\cdot a)(b \\times b)$$\nSince $b \\times b = \\vec{0}$, we have:\n$$v \\times b = (a \\cdot b)(a \\times b)$$\nThus, $v \\times b$ is directly a scalar multiple of $(a \\times b)$ with scaling constant $(a \\cdot b)$. Therefore, they are always collinear.',
    intuition: 'Vector triple cross products represent rotations and orthogonal projections in 3D Euclidean space. The BAC-CAB identity translates complex cross products into basic linear combinations of the constituent bases, demonstrating how complex vector fields simplify under matrix transformations.',
    tags: ['vector-identities', 'collinearity-proof', 'cross-product', '3D-vectors']
  }
];
